name: foodfinder_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.1.0
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  fonts:
    - family: Afacad
      fonts:
        - asset: fonts/Afacad-VariableFont_wght.ttf
